### ISSUE TITLE
error in reading abacus output file

### ISSUE THREAD

**Issue by hongriTianqi** [1041176461/abacus-ase#1]
This is the output file for an ase-abcus opt calculation after the first abacus calculation step:
[running_scf.log](https://github.com/1041176461/abacus-ase/files/9080758/running_scf.log)

This is the error:
<img width="1196" alt="ase-abacus-lcao-opt" src="https://user-images.githubusercontent.com/18049272/178184666-ed1c3b57-0d1e-413a-bcba-5aa643fb40e3.PNG">

**Comment by hongriTianqi** [comment]
<img width="1196" alt="ase-abacus-lcao-opt" src="https://user-images.githubusercontent.com/18049272/178184724-67c43a31-ae34-4ab5-982c-80121a7c8f10.PNG">

**Comment by 1041176461** [comment]
Thank you for your report ! This bug occurs because there are extra column with title 'ibz2bz' and row 'is_mp : ' in recent version of ABACUS (I'm not sure which version introduced it). I update my code to sync with these new modification. Please try it again.
