### ISSUE TITLE
variable-cell optimiazation not supported in the current ase interface

### ISSUE THREAD

**Issue by hongriTianqi** [1041176461/abacus-ase#2]
Dear Author,
I have found that the variable-cell optimiazation is not supported yet in the current ase interface codes. I have attached my example in the following. Please have a look? Thanks!
[examples.tar.gz](https://github.com/1041176461/abacus-ase/files/9091095/examples.tar.gz)

The error happens as follows:
<img width="1501" alt="ff" src="https://user-images.githubusercontent.com/18049272/178446397-ff839e22-64bb-4435-aeaf-5041494b7758.PNG">

**Comment by 1041176461** [comment]
Thank you for your report. I have fixed this bug in new commit. Please try it again.

**Comment by hongriTianqi** [comment]
> This problem may not stem from the interface. Could you please try it again with some different input settings?

Thanks! I modified the input files. I see no error like above now. However, the optimization process goes without ending now. There is no output of FMAX and SMAX from ASE now. The new testing files are attached here. Could you please have a look again?
[examples1.tar.gz](https://github.com/1041176461/abacus-ase/files/9107288/examples1.tar.gz)

**Comment by 1041176461** [comment]
> > This problem may not stem from the interface. Could you please try it again with some different input settings?
> 
> Thanks! I modified the input files. I see no error like above now. However, the optimization process goes without ending now. There is no output of FMAX and SMAX from ASE now. The new testing files are attached here. Could you please have a look again? [examples1.tar.gz](https://github.com/1041176461/abacus-ase/files/9107288/examples1.tar.gz)

The error results from that there are two different formats and units of stress tensors of ASE and ABACUS, but I forgot to convert it in the interface. In the new commit, I fix this bug, then the optimization process can end successfully.

**Comment by hzl1230** [comment]
> > > This problem may not stem from the interface. Could you please try it again with some different input settings?
> > 
> > 
> > Thanks! I modified the input files. I see no error like above now. However, the optimization process goes without ending now. There is no output of FMAX and SMAX from ASE now. The new testing files are attached here. Could you please have a look again? [examples1.tar.gz](https://github.com/1041176461/abacus-ase/files/9107288/examples1.tar.gz)
> 
> The error results from that there are two different formats and units of stress tensors of ASE and ABACUS, but I forgot to convert it in the interface. In the new commit, I fix this bug, then the optimization process can end successfully. Thanks for your report!

hello, this bug has been fixed now? I met this problem and dont know how to deal it.Looking  forward to you reply.
